[mgr]
prepend_keymap = [
  { on = [ "T", "n"], run = "shell -- zellij action new-tab --cwd %s1", desc = "Open current in new Zellij tab" },
  { on = [ "T", "l" ], run = "shell -- zellij run -c -d right -- nu -c 'cd %s1 ; exec nu'", desc = "Open current in right pane" },
  { on = [ "T", "j" ], run = "shell -- zellij run -c -d down -- nu -c 'cd %s1 ; exec nu'", desc = "Open current in lower pane" },
  { on = [ "H", "n"], run = "shell -- zellij action new-tab --close-on-exit -- hx %s1", desc = "Open current in Helix in new tab" },
  { on = [ "H", "l"], run = "shell -- zellij run -c -d right -- hx %s1", desc = "Open current in Helix in right pane" },
]

